### ISSUE TITLE
Location picker uses an old version of the package intl

### ISSUE THREAD

**Issue by cdiethelm** [Michael-M-aher/location_picker_flutter_map#58]
New flutter apps depend on intl ^0.20.2 with the new flutter sdk 3.32.0.

`Because every version of flutter_localizations from sdk depends on intl 0.20.2 and XXX depends on intl ^0.19.0, flutter_localizations from sdk is forbidden.`

When updating my app to version ^0.20.2, the following occurs: 

`Because location_picker_flutter_map 3.1.0 depends on intl ^0.19.0 and no versions of location_picker_flutter_map match >3.1.0 <4.0.0, location_picker_flutter_map ^3.1.0 requires intl ^0.19.0.`

**Comment by sawongam** [comment]
I've opened a PR to fix this intl dependency issue. Until it gets merged, you can use my fork as a temporary solution:
```
  location_picker_flutter_map:
    git:
      url: https://github.com/sawongam/location_picker_flutter_map
      ref: main
```
This resolves the conflict with Flutter SDK 3.32.5 and intl ^0.20.2.
